import { test, expect } from '@playwright/test'

test('collection acceptance: exact finishes, rollup, preference, detail magnification and persistence',async({page,request,context})=>{
 test.setTimeout(90000)
 const query='category=Trainer&q=Ultra+Ball'
 const pool=await (await request.get('/api/v1/cards?'+query+'&include_image=true')).json()
 expect(pool.cards.length).toBeGreaterThan(0)
 const anchor=pool.cards[0],variant=anchor.ownership.variant
 const choices=await (await request.get(`/api/v1/cards/${anchor.id}/variations?page_size=24`)).json()
 const other=choices.cards.find((c:any)=>c.id!==anchor.id && c.ownership.variant!=='unspecified')
 expect(other).toBeTruthy()
 const otherVariant=other.ownership.variant
 const display=choices.cards.find((c:any)=>c.id===other.id && c.ownership.variant!==otherVariant)
 expect(display).toBeTruthy()
 const displayVariant=display.ownership.variant
 await page.goto('/?'+query)
 const tile=()=>page.locator(`article[data-printing-id="${anchor.id}"]`)
 await expect(tile().getByLabel('Total owned',{exact:true})).toHaveText('0')
 await tile().locator('.card-art').hover();await expect(page.locator('.art-preview')).toHaveCount(0)
 await tile().getByRole('button',{name:`Add one ${anchor.id} ${variant}`,exact:true}).focus()
 await page.keyboard.press('Enter')
 await expect(tile().getByLabel('Total owned',{exact:true})).toHaveText('1')
 await tile().getByRole('button',{name:`Add one ${anchor.id} ${variant}`,exact:true}).click()
 await expect(tile().getByLabel('Total owned',{exact:true})).toHaveText('2')
 const libraryURL=page.url()
 await tile().getByRole('link').click()
 await expect(page.getByLabel('Exact variation owned',{exact:true})).toHaveText('2')
 const primary=page.locator('.detail-art .card-art')
 const normal=await primary.boundingBox()
 const frame=await page.locator('.detail-art .artwork-frame').boundingBox()
 const text=await page.locator('.detail-layout>section').boundingBox()
 await primary.hover()
 expect(await primary.boundingBox()).toEqual(normal)
 expect(await page.locator('.detail-art .artwork-frame').boundingBox()).toEqual(frame)
 expect(await page.locator('.detail-layout>section').boundingBox()).toEqual(text)
 await expect(page.locator('.art-preview')).toHaveCount(0)
 await expect(page.getByRole('tooltip')).toHaveCount(0)
 await expect(page.getByRole('button',{name:'Enlarge artwork',exact:true})).toHaveCount(0)
 await expect(page.locator('.detail-art .artwork-hint')).toHaveText('Click to enlarge')
 await page.getByRole('heading',{name:'Card text',exact:true}).hover()
 expect((await primary.boundingBox())!.width).toBeCloseTo(normal!.width,0)
 await page.getByRole('button',{name:`Enlarge ${anchor.name} ${anchor.id}`,exact:true}).focus()
 await page.keyboard.press('Enter')
 await expect(page.getByRole('dialog',{name:`Artwork ${anchor.id}`,exact:true})).toBeVisible()
 await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0)
 await page.getByRole('button',{name:'Variations',exact:true}).click()
 const otherTile=page.locator(`[data-variation="${other.id}:${otherVariant}"]`)
 await expect(otherTile).toContainText('Not owned')
 await otherTile.scrollIntoViewIfNeeded()
 expect(await otherTile.locator('.card-art img').evaluate((img)=>({opacity:getComputedStyle(img).opacity,filter:getComputedStyle(img).filter}))).toEqual({opacity:'1',filter:'none'})
 await otherTile.getByRole('button',{name:`Add one ${other.id} ${otherVariant}`,exact:true}).click()
 await expect(otherTile.getByLabel('Exact variation owned',{exact:true})).toHaveText('1')
 await expect(page.getByLabel('Functional total',{exact:true})).toHaveText('3')
 await otherTile.getByRole('link',{name:`Inspect ${other.id} ${otherVariant}`,exact:true}).focus()
 await page.keyboard.press('Enter')
 await expect(page).toHaveURL(new RegExp(`/cards/${other.id}\\?variant=${otherVariant}`))
 await expect(page.locator('.detail-art').getByLabel('Exact variation owned',{exact:true})).toHaveText('1')
 await page.mouse.move(1400,10)
 expect((await primary.boundingBox())!.width).toBeCloseTo(normal!.width,0)
 const pref=await (await request.get(`/api/v1/library/${anchor.id}/preference`)).json()
 expect(pref.printing_id).toBe(anchor.id)
 await page.getByRole('link',{name:'← Back to library'}).click();await expect(page).toHaveURL(libraryURL)
 await expect(tile().getByLabel('Total owned',{exact:true})).toHaveText('3')
 await page.getByRole('button',{name:'Owned',exact:true}).click()
 await expect(tile()).toHaveCount(1)
 await expect(page).toHaveURL(/ownership=owned/)
 await page.getByRole('button',{name:'Unowned',exact:true}).click()
 await expect(page.getByRole('region',{name:'Card library results'})).toHaveAttribute('aria-busy','false')
 await expect(tile()).toHaveCount(0)
 await page.getByRole('button',{name:'All',exact:true}).click()
 await tile().getByRole('button',{name:'Choose artwork / finish'}).click()
 await page.getByRole('button',{name:`Use ${display.id} ${displayVariant} in Library`,exact:true}).click()
 const preferred=()=>page.locator(`article[data-printing-id="${display.id}"]`)
 await expect(preferred().getByRole('button',{name:`Remove one ${display.id} ${displayVariant}`,exact:true})).toBeDisabled()
 await expect(preferred().getByLabel('Total owned',{exact:true})).toHaveText('3')
 await preferred().getByRole('button',{name:`Add one ${display.id} ${displayVariant}`,exact:true}).click()
 await expect(preferred().getByLabel('Total owned',{exact:true})).toHaveText('4')
 await page.reload();await expect(preferred().getByLabel('Total owned',{exact:true})).toHaveText('4')
 const fresh=await context.newPage();await fresh.goto(libraryURL)
 await expect(fresh.locator(`article[data-printing-id="${display.id}"]`).getByLabel('Total owned',{exact:true})).toHaveText('4');await fresh.close()
 await page.getByRole('button',{name:'Collection',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Collection',exact:true})).toBeVisible()
 await expect(page.locator('article')).toHaveCount(3)
 await page.getByRole('button',{name:'List',exact:true}).click();await expect(page.locator('.card-row')).toHaveCount(3)
 await page.screenshot({path:'test-results/phase3-collection.png',fullPage:true})
 await page.getByRole('button',{name:'Library',exact:true}).click();await expect(page).toHaveURL(libraryURL)
 await preferred().getByRole('link').click()
 await page.getByRole('button',{name:'Variations',exact:true}).click()
 await expect(page.locator('.variation-card').first()).toBeVisible()
 await page.screenshot({path:'test-results/phase3-variations.png',fullPage:true})
})

test('PM cleanup geometry, bounded variations and Collection row ownership',async({page,request})=>{
 await page.setViewportSize({width:2200,height:1400})
 const pool=await (await request.get('/api/v1/cards?category=Trainer&q=Ultra+Ball')).json()
 const anchor=pool.cards[0]
 const choices=await (await request.get(`/api/v1/cards/${anchor.id}/variations`)).json()
 expect(choices.cards.every((c:any)=>c.ownership.variant!=='unspecified')).toBe(true)
 await page.goto(`/cards/${anchor.id}?variant=${anchor.ownership.variant}`)
 await expect(page.locator('.detail-art .artwork-frame')).toBeVisible()
 await page.mouse.move(2190,10)
 const primary=page.locator('.detail-art .card-art')
 const box=await primary.boundingBox(),frame=await page.locator('.detail-art .artwork-frame').boundingBox()
 expect(box!.width).toBeCloseTo(250,0)
 const enlarge=await page.locator('.detail-art .artwork-hint').boundingBox()
 expect(enlarge!.x+enlarge!.width/2).toBeCloseTo(frame!.x+frame!.width/2,0)
 const buttons=page.locator('.detail-art .quantity-row button')
 const minus=await buttons.first().boundingBox(),plus=await buttons.last().boundingBox()
 expect((minus!.x+plus!.x+plus!.width)/2).toBeCloseTo(frame!.x+frame!.width/2,0)
 expect(minus!.y).toBeGreaterThan(frame!.y+frame!.height)
 await page.getByRole('button',{name:'Variations',exact:true}).click()
 await expect(page.locator('.variation-card').first()).toBeVisible()
 const widths=await page.locator('.variation-card .embedded-artwork').evaluateAll(els=>els.map(el=>el.getBoundingClientRect().width))
 expect(widths.every(width=>Math.abs(width-box!.width)<1)).toBe(true)
 expect(await page.locator('.variation-grid').evaluate(el=>getComputedStyle(el).gridTemplateColumns.split(' ').length)).toBe(4)
 await page.locator('.variation-grid').scrollIntoViewIfNeeded()
 const visibleArtwork=page.locator('.variation-card .card-art img')
 for(let i=0;i<Math.min(4,await visibleArtwork.count());i++) {
  await expect(visibleArtwork.nth(i)).toHaveJSProperty('complete',true)
  await expect.poll(()=>visibleArtwork.nth(i).evaluate((img:HTMLImageElement)=>img.naturalWidth)).toBeGreaterThan(0)
 }
 await page.screenshot({path:'test-results/phase3-cleanup-variations-large.png',fullPage:true})
 for(const card of choices.cards.slice(0,3)) {
  await page.getByRole('link',{name:`Inspect ${card.id} ${card.ownership.variant}`,exact:true}).click()
  await expect(page.locator('.detail-art').getByRole('button',{name:`Add one ${card.id} ${card.ownership.variant}`,exact:true})).toBeVisible()
  await page.mouse.move(2190,10)
  expect((await primary.boundingBox())!.width).toBeCloseTo(box!.width,0)
  expect((await primary.boundingBox())!.height).toBeCloseTo(box!.height,0)
  await primary.click()
  await expect(page.getByRole('dialog',{name:`Artwork ${card.id}`,exact:true})).toBeVisible()
  await expect(page.locator('.enlarged-art')).toHaveAttribute('alt',`${card.name} — ${card.id}`)
  await page.keyboard.press('Escape')
 }
 // Legacy unknown-finish ownership is still editable but never an extra finish tile.
 await request.put(`/api/v1/collection/${anchor.id}`,{data:{variant:'unspecified',quantity:2}})
 await page.goto(`/cards/${anchor.id}`)
 await expect(page.locator('.detail-art')).toContainText('Finish not recorded')
 await page.getByRole('button',{name:'Variations',exact:true}).click()
 await expect(page.getByRole('region',{name:'Copies with no recorded finish'})).toBeVisible()
 await expect(page.locator('.variation-grid')).not.toContainText('Finish not recorded')
 expect(await page.locator('body').innerText()).not.toContain('unspecified')
 await page.getByRole('button',{name:'Collection',exact:true}).click()
 await page.getByRole('button',{name:'List',exact:true}).click()
 await expect(page.locator('.card-row').first()).toBeVisible()
 const rows=await page.locator('.card-row').evaluateAll(els=>els.map(el=>{
  const row=el.getBoundingClientRect(),controls=el.querySelector('.ownership-controls')!.getBoundingClientRect(),link=el.querySelector('.card-link')!
  return {inside:controls.bottom<row.bottom,border:getComputedStyle(el).borderBottomWidth,linkBorder:getComputedStyle(link).borderBottomWidth}
 }))
 expect(rows.every(r=>r.inside&&r.border==='1px'&&r.linkBorder==='0px')).toBe(true)
 expect(await page.locator('body').innerText()).not.toContain('unspecified')
 await page.getByRole('button',{name:`Remove one ${anchor.id} Finish not recorded`,exact:true}).click()
 await expect(page.locator(`article[data-printing-id="${anchor.id}"]`).filter({has:page.getByRole('button',{name:`Add one ${anchor.id} Finish not recorded`,exact:true})}).getByLabel('Exact variation owned',{exact:true})).toHaveText('1')
 await page.screenshot({path:'test-results/phase3-cleanup-collection-rows.png',fullPage:true})
})
