import { test, expect } from '@playwright/test'

test('collection acceptance: exact finishes, rollup, preference, detail magnification and persistence',async({page,request,context})=>{
 test.setTimeout(90000)
 const query='category=Trainer&q=Ultra+Ball'
 const pool=await (await request.get('/api/v1/cards?'+query+'&include_image=true')).json()
 expect(pool.cards.length).toBeGreaterThan(0)
 const anchor=pool.cards[0],variant=anchor.ownership.variant
 const choices=await (await request.get(`/api/v1/cards/${anchor.id}/variations?page_size=24`)).json()
 const other=choices.cards.find((c:any)=>c.id!==anchor.id && c.ownership.variant!=='unspecified')
 expect(other).toBeTruthy()
 const otherVariant=other.ownership.variant
 const display=choices.cards.find((c:any)=>c.id===other.id && c.ownership.variant==='unspecified')
 expect(display).toBeTruthy()
 await page.goto('/?'+query)
 const tile=()=>page.locator(`article[data-printing-id="${anchor.id}"]`)
 await expect(tile().getByLabel('Total owned',{exact:true})).toHaveText('0')
 await tile().locator('.card-art').hover();await expect(page.locator('.art-preview')).toHaveCount(0)
 await tile().getByRole('button',{name:`Add one ${anchor.id} ${variant}`,exact:true}).focus()
 await page.keyboard.press('Enter')
 await expect(tile().getByLabel('Total owned',{exact:true})).toHaveText('1')
 await tile().getByRole('button',{name:`Add one ${anchor.id} ${variant}`,exact:true}).click()
 await expect(tile().getByLabel('Total owned',{exact:true})).toHaveText('2')
 const libraryURL=page.url()
 await tile().getByRole('link').click()
 await expect(page.getByLabel('Exact variation owned',{exact:true})).toHaveText('2')
 await page.locator('.detail-art .card-art').hover()
 await expect(page.locator('.art-preview')).toBeVisible()
 await expect(page.getByRole('tooltip')).toHaveCount(0)
 await page.getByRole('heading',{name:'Card text',exact:true}).hover()
 await expect(page.locator('.art-preview')).toHaveCount(0)
 await page.getByRole('button',{name:`Enlarge ${anchor.name} ${anchor.id}`,exact:true}).focus()
 await page.keyboard.press('Enter')
 await expect(page.getByRole('dialog',{name:`Artwork ${anchor.id}`,exact:true})).toBeVisible()
 await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0)
 await page.getByRole('button',{name:'Variations',exact:true}).click()
 const otherTile=page.locator(`[data-variation="${other.id}:${otherVariant}"]`)
 await expect(otherTile).toContainText('Not owned')
 await otherTile.scrollIntoViewIfNeeded()
 expect(await otherTile.locator('.card-art img').evaluate((img)=>({opacity:getComputedStyle(img).opacity,filter:getComputedStyle(img).filter}))).toEqual({opacity:'1',filter:'none'})
 await otherTile.getByRole('button',{name:`Add one ${other.id} ${otherVariant}`,exact:true}).click()
 await expect(otherTile.getByLabel('Exact variation owned',{exact:true})).toHaveText('1')
 await expect(page.getByLabel('Functional total',{exact:true})).toHaveText('3')
 await otherTile.getByRole('link',{name:`Inspect ${other.id} ${otherVariant}`,exact:true}).focus()
 await page.keyboard.press('Enter')
 await expect(page).toHaveURL(new RegExp(`/cards/${other.id}\\?variant=${otherVariant}`))
 await expect(page.locator('.detail-art').getByLabel('Exact variation owned',{exact:true})).toHaveText('1')
 const pref=await (await request.get(`/api/v1/library/${anchor.id}/preference`)).json()
 expect(pref.printing_id).toBe(anchor.id)
 await page.getByRole('link',{name:'← Back to library'}).click();await expect(page).toHaveURL(libraryURL)
 await expect(tile().getByLabel('Total owned',{exact:true})).toHaveText('3')
 await page.getByRole('button',{name:'Owned',exact:true}).click()
 await expect(tile()).toHaveCount(1)
 await expect(page).toHaveURL(/ownership=owned/)
 await page.getByRole('button',{name:'Unowned',exact:true}).click()
 await expect(page.getByRole('region',{name:'Card library results'})).toHaveAttribute('aria-busy','false')
 await expect(tile()).toHaveCount(0)
 await page.getByRole('button',{name:'All',exact:true}).click()
 await tile().getByRole('button',{name:'Choose artwork / finish'}).click()
 await page.getByRole('button',{name:`Use ${display.id} unspecified in Library`,exact:true}).click()
 const preferred=()=>page.locator(`article[data-printing-id="${display.id}"]`)
 await expect(preferred().getByRole('button',{name:`Remove one ${display.id} unspecified`,exact:true})).toBeDisabled()
 await expect(preferred().getByLabel('Total owned',{exact:true})).toHaveText('3')
 await preferred().getByRole('button',{name:`Add one ${display.id} unspecified`,exact:true}).click()
 await expect(preferred().getByLabel('Total owned',{exact:true})).toHaveText('4')
 await page.reload();await expect(preferred().getByLabel('Total owned',{exact:true})).toHaveText('4')
 const fresh=await context.newPage();await fresh.goto(libraryURL)
 await expect(fresh.locator(`article[data-printing-id="${display.id}"]`).getByLabel('Total owned',{exact:true})).toHaveText('4');await fresh.close()
 await page.getByRole('button',{name:'Collection',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Collection',exact:true})).toBeVisible()
 await expect(page.locator('article')).toHaveCount(3)
 await page.getByRole('button',{name:'List',exact:true}).click();await expect(page.locator('.card-row')).toHaveCount(3)
 await page.screenshot({path:'test-results/phase3-collection.png',fullPage:true})
 await page.getByRole('button',{name:'Library',exact:true}).click();await expect(page).toHaveURL(libraryURL)
 await preferred().getByRole('link').click()
 await page.getByRole('button',{name:'Variations',exact:true}).click()
 await expect(page.locator('.variation-card').first()).toBeVisible()
 await page.screenshot({path:'test-results/phase3-variations.png',fullPage:true})
})
