import { test, expect, type APIRequestContext } from '@playwright/test'

async function command(request:APIRequestContext,body:object){
 const current=await (await request.get('/api/v1/deck-workspace')).json()
 const response=await request.post('/api/v1/deck-workspace',{data:{...body,schema_version:2,revision:current.revision}})
 expect(response.ok()).toBeTruthy();return response.json()
}
test.beforeEach(async({request})=>{await command(request,{action:'new',discard:true})})

test('builder reuses browsing, read-only ownership, tray, detail, research, and navigation',async({page,request},info)=>{
 test.setTimeout(120000)
 const pool=await (await request.get('/api/v1/cards?category=Pokemon&stages=Basic&page_size=24')).json()
 const card=pool.cards[0],query='category=Pokemon&stages=Basic'
 const ownership=await (await request.get(`/api/v1/cards/${card.id}/ownership?variant=${card.ownership.variant}`)).json()
 const writes:string[]=[]
 page.on('request',r=>{if(r.method()==='PUT')writes.push(r.url())})
 await page.goto('/deck-builder?'+query)
 const tray=page.getByRole('complementary',{name:'Active deck'})
 await expect(tray).toContainText('EMPTY')
 const tile=page.locator(`[data-printing-id="${card.id}"]`)
 await expect(tile).toBeVisible()
 await expect(tile.getByRole('button',{name:/Add one|Remove one/})).toHaveCount(0)
 await tile.getByRole('button',{name:`Add ${card.name} to deck`,exact:true}).click({clickCount:3,delay:40})
 await expect(tile.getByLabel(`${card.name} deck quantity`,{exact:true})).toHaveText('3')
 await expect(tray).toContainText('IN PROGRESS')
 await page.getByRole('button',{name:'List',exact:true}).click()
 await expect(page.locator('.card-row').first()).toBeVisible()
 await tile.getByRole('link').click()
 await expect(page).toHaveURL(/\/deck-builder\/cards\//)
 await expect(tray).toContainText(card.name)
 await expect(page.locator('.detail-art')).toContainText('Function total:')
 await expect(page.locator('.detail-art').getByRole('button',{name:/Add one|Remove one/})).toHaveCount(0)
 await page.getByRole('button',{name:'Variations',exact:true}).click()
 await expect(page.locator('.variation-card').first()).toBeVisible()
 await expect(page.locator('.variations-section').getByRole('button',{name:/Add one|Remove one/})).toHaveCount(0)
 await page.getByRole('heading',{name:'Competitive research',exact:true}).scrollIntoViewIfNeeded()
 await expect(tray).toBeInViewport()
 await page.screenshot({path:info.outputPath('builder-research.png')})
 await page.getByRole('link',{name:'← Back to Deck Builder'}).click()
 await expect(page).toHaveURL('/deck-builder?'+query)
 await expect(page.getByRole('button',{name:'List',exact:true})).toHaveAttribute('aria-pressed','true')
 await expect(page.getByLabel('Basic',{exact:true})).toBeChecked()
 await page.getByRole('button',{name:'Gallery',exact:true}).click()
 await page.getByRole('button',{name:'Toggle filters',exact:true}).click()
 await expect.poll(()=>tile.locator('.card-art img').evaluateAll(imgs=>imgs.some(img=>(img as HTMLImageElement).naturalWidth>0)),{timeout:45000}).toBeTruthy()
 await page.screenshot({path:info.outputPath('builder-gallery-1440.png')})
 await page.setViewportSize({width:1100,height:800})
 await expect(tray).toBeInViewport()
 await expect(tile.getByRole('button',{name:`Add ${card.name} to deck`,exact:true})).toBeInViewport()
 await page.screenshot({path:info.outputPath('builder-gallery-1100.png')})
 await page.getByRole('button',{name:'PokéLab Home'}).click();await expect(page).toHaveURL('/')
 await expect(tray).toHaveCount(0)
 await page.getByRole('button',{name:'Deck Builder',exact:true}).click()
 await expect(page).toHaveURL('/deck-builder?'+query)
 await expect(tray).toContainText(card.name)
 expect(writes).toEqual([])
 expect(await (await request.get(`/api/v1/cards/${card.id}/ownership?variant=${card.ownership.variant}`)).json()).toEqual(ownership)
})

test('builder competitive hover uses artwork only at half a second and Full Research retains context',async({page})=>{
 await page.goto('/deck-builder?category=Trainer&q=Ultra+Ball')
 const tile=page.locator('[data-printing-id]').first();await expect(tile).toBeVisible()
 await page.clock.install();await page.clock.pauseAt(new Date(Date.now()+1000))
 await tile.locator('.card-art img').hover();await page.clock.runFor(499)
 await expect(page.locator('.competitive-popup')).toHaveCount(0)
 await page.clock.runFor(1)
 const popup=page.getByRole('dialog',{name:/competitive preview/});await expect(popup).toBeVisible()
 await popup.hover();await page.clock.runFor(200)
 await popup.getByRole('link',{name:'Click for full research →'}).click()
 await expect(page).toHaveURL(/\/deck-builder\/cards\//)
 await expect(page.getByRole('heading',{name:'Competitive research',exact:true})).toBeVisible()
 await expect(page.getByRole('complementary',{name:'Active deck'})).toBeVisible()
 await page.getByRole('link',{name:'← Back to Deck Builder'}).click()
 await expect(page.getByRole('textbox',{name:'Search cards'})).toHaveValue('Ultra Ball')
 await expect(page.getByRole('button',{name:'Trainers',exact:true})).toHaveAttribute('aria-pressed','true')
})

test('draft persistence, save-state validation, New guard, reopen and selected finish',async({page,request},info)=>{
 test.setTimeout(120000)
 const pool=await (await request.get('/api/v1/cards?category=Pokemon&stages=Basic')).json()
 const card=pool.cards[0]
 await command(request,{action:'quantity',printing_id:card.id,delta:1})
 await page.goto('/deck-builder')
 const tray=page.getByRole('complementary',{name:'Active deck'});await expect(tray).toContainText('IN PROGRESS')
 await tray.getByRole('button',{name:'Rename',exact:true}).click()
 await tray.getByRole('textbox',{name:'Deck name'}).fill('Phase 5 browser draft')
 await tray.getByRole('button',{name:'Apply name'}).click()
 await expect(tray.getByRole('heading',{name:'Phase 5 browser draft'})).toBeVisible()
 await tray.getByRole('button',{name:'Save',exact:true}).click()
 await expect(tray).toContainText('INVALID');await expect(tray).toContainText('59 cards remaining')
 await page.reload();await expect(tray).toContainText('Phase 5 browser draft');await expect(tray).toContainText('INVALID')
 await tray.getByRole('link',{name:card.name,exact:true}).click()
 await page.getByRole('button',{name:'Variations',exact:true}).click()
 const choice=page.locator('.variation-card').first();await expect(choice).toBeVisible()
 await expect(choice.getByRole('button',{name:/default printing/i})).toHaveCount(0)

 await page.locator('.detail-art').getByRole('button',{name:'Add '+card.name+' to deck',exact:true}).click()
 await expect(tray.locator('footer')).toContainText('Draft stored')
 page.once('dialog',dialog=>dialog.dismiss())
 await tray.getByRole('button',{name:'New',exact:true}).click();await expect(tray).toContainText(card.name)
 await tray.getByRole('button',{name:'Save',exact:true}).click()
 await expect(tray.locator('footer')).toContainText('Saved')
 const selected=(await (await request.get('/api/v1/deck-workspace')).json()).deck.entries[0]
 await tray.getByRole('button',{name:'New',exact:true}).click();await expect(tray).toContainText('EMPTY')
 await tray.getByRole('button',{name:'Open',exact:true}).click()
 await tray.getByRole('button',{name:'Phase 5 browser draft',exact:true}).click()
 await expect(tray).toContainText('58 cards remaining')
 const reopened=(await (await request.get('/api/v1/deck-workspace')).json()).deck.entries[0]
 expect(reopened).toEqual(selected)
 await tray.getByRole('button',{name:`Increase ${card.name} in tray`,exact:true}).click()
 await expect(tray).toContainText('57 cards remaining')
 await page.screenshot({path:info.outputPath('builder-saved-incomplete.png')})
})

test('save failure is surfaced and draft remains recoverable',async({page,request})=>{
 const card=(await (await request.get('/api/v1/cards?category=Pokemon&stages=Basic')).json()).cards[0]
 await command(request,{action:'quantity',printing_id:card.id,delta:1})
 await page.goto('/deck-builder');const tray=page.getByRole('complementary',{name:'Active deck'})
 await expect(tray).toContainText('IN PROGRESS')
 await page.route('**/api/v1/deck-workspace',async route=>{
  if(route.request().method()==='POST'&&route.request().postDataJSON().action==='save')await route.fulfill({status:503,json:{detail:'Simulated disk failure'}})
  else await route.continue()
 })
 await tray.getByRole('button',{name:'Save',exact:true}).click()
 await expect(tray.getByRole('alert')).toContainText('Simulated disk failure')
 await expect(tray).toContainText(card.name)
 await tray.getByRole('button',{name:'Reload stored draft'}).click()
 await expect(tray.getByRole('alert')).toHaveCount(0)
 await expect(tray).toContainText('IN PROGRESS')
})

test('dense real-card deck scrolls independently, valid and invalid states, keyboard artwork',async({page,request},info)=>{
 test.setTimeout(150000)
 const pool=await (await request.get('/api/v1/cards?category=Pokemon&stages=Basic&page_size=50')).json()
 const names=new Set<string>()
 const cards=pool.cards.filter((c:any)=>{if(names.has(c.name))return false;names.add(c.name);return true}).slice(0,20)
 expect(cards).toHaveLength(20)
 let state=await (await request.get('/api/v1/deck-workspace')).json()
 for(const card of cards)for(let n=0;n<3;n++){
  const response=await request.post('/api/v1/deck-workspace',{data:{schema_version:2,action:'quantity',revision:state.revision,printing_id:card.id,delta:1}})
  expect(response.ok()).toBeTruthy();state=await response.json()
 }
 expect(state.validation.state).toBe('VALID')
 await page.setViewportSize({width:1280,height:900})
 await page.goto('/deck-builder?stages=Basic')
 const tray=page.getByRole('complementary',{name:'Active deck'})
 await expect(tray.locator('.deck-state')).toHaveText('VALID')
 await expect(tray).toContainText('60 / 60')
 await expect(page.locator('[data-printing-id]')).toHaveCount(24)
 await expect.poll(()=>page.locator('.card-art img').evaluateAll(imgs=>imgs.some(img=>(img as HTMLImageElement).naturalWidth>0)),{timeout:45000}).toBeTruthy()
 await page.screenshot({path:info.outputPath('builder-valid-dense-1280.png')})
 const last=tray.getByRole('link',{name:cards[19].name,exact:true})
 await last.scrollIntoViewIfNeeded();await expect(last).toBeInViewport()
 await expect(tray.getByRole('button',{name:'Save',exact:true})).toBeInViewport()
 await expect.poll(()=>tray.locator('.deck-entries').evaluate(el=>el.scrollTop)).toBeGreaterThan(0)
 await last.focus();await page.keyboard.press('Enter')
 const enlarge=page.getByRole('button',{name:`Enlarge ${cards[19].name} ${cards[19].id}`,exact:true})
 await expect(enlarge).toBeEnabled();await enlarge.focus();await page.keyboard.press('Enter')
 await expect(page.getByRole('dialog',{name:`Artwork ${cards[19].id}`,exact:true})).toBeVisible()
 await page.keyboard.press('Escape')
 await expect(page.getByRole('dialog')).toHaveCount(0)
 await page.locator('.detail-art').getByRole('button',{name:`Add ${cards[19].name} to deck`,exact:true}).click()
 await expect(tray.locator('.deck-state')).toHaveText('INVALID')
 await expect(tray).toContainText('61 cards')
 await page.getByRole('button',{name:'Toggle Agent panel'}).click()
 await expect(page.getByLabel('PokéLab Agent')).toContainText('No AI provider is connected')
 await expect(tray).toBeInViewport()
 await page.screenshot({path:info.outputPath('builder-invalid-agent-1280.png')})
})

test('long names wrap in tray and gallery scroll returns after inspection',async({page,request})=>{
 const pool=await (await request.get('/api/v1/cards?category=Pokemon&q=Team+Rocket&page_size=50')).json()
 const card=pool.cards.sort((a:any,b:any)=>b.name.length-a.name.length)[0]
 expect(card.name.length).toBeGreaterThan(20)
 await page.goto('/deck-builder?category=Pokemon&q='+encodeURIComponent(card.name))
 const tile=page.locator(`[data-printing-id="${card.id}"]`)
 await expect(tile).toBeVisible()
 await tile.getByRole('button',{name:`Add ${card.name} to deck`,exact:true}).click()
 const tray=page.getByRole('complementary',{name:'Active deck'})
 const name=tray.getByRole('link',{name:card.name,exact:true})
 await expect(name).toBeVisible()
 expect(await name.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBeTruthy()
 await page.getByRole('button',{name:'Clear search'}).click()
 const gallery=page.getByRole('region',{name:'Card library results'})
 await expect(gallery).toHaveAttribute('aria-busy','false')
 await gallery.evaluate(el=>{el.scrollTop=500})
 await expect.poll(()=>gallery.evaluate(el=>el.scrollTop)).toBeGreaterThan(0)
 const candidate=page.locator('[data-printing-id]').nth(12)
 await candidate.scrollIntoViewIfNeeded()
 const position=await gallery.evaluate(el=>el.scrollTop)
 await candidate.getByRole('link').click()
 await expect(page.getByRole('heading',{name:'Card text',exact:true})).toBeVisible()
 await page.getByRole('link',{name:'← Back to Deck Builder'}).click()
 await expect(gallery).toHaveAttribute('aria-busy','false')
 await expect.poll(()=>gallery.evaluate(el=>el.scrollTop)).toBeCloseTo(position,0)
 await expect(tray.getByRole('link',{name:card.name,exact:true})).toBeVisible()
})
