import { test, expect } from '@playwright/test'

test('categories, search, OR/AND filters, paging, views, exact detail and history',async({page})=>{
 await page.route('https://api.tcgdex.net/**',()=>{throw new Error('Unexpected card-data request')})
 await page.goto('/')
 await expect(page.locator('article')).toHaveCount(24)
 await page.getByRole('button',{name:'Trainers',exact:true}).click()
 await page.getByRole('textbox',{name:'Search cards'}).fill('bOsS')
 await expect(page.locator('article').first()).toContainText(/Boss/i)
 await page.getByLabel('Supporter',{exact:true}).click(); await expect(page.getByLabel('Supporter',{exact:true})).toBeChecked()
 await expect(page.locator('article').first()).toContainText('Supporter')
 await page.getByRole('button',{name:'Clear search'}).click()
 await page.getByRole('button',{name:'Energy',exact:true}).click()
 await page.getByLabel('Special Energy',{exact:true}).click(); await expect(page.getByLabel('Special Energy',{exact:true})).toBeChecked()
 await expect(page.locator('article').first()).toContainText('Special Energy')
 await page.getByRole('button',{name:'Pokémon',exact:true}).click()
 await page.getByLabel('Psychic',{exact:true}).click(); await expect(page.getByLabel('Psychic',{exact:true})).toBeChecked()
 await page.getByLabel('Dragon',{exact:true}).click(); await expect(page.getByLabel('Dragon',{exact:true})).toBeChecked()
 await page.getByLabel('Basic',{exact:true}).click(); await expect(page.getByLabel('Basic',{exact:true})).toBeChecked()
 await page.getByRole('textbox',{name:'Search cards'}).fill('a')
 await expect(page.getByRole('button',{name:'Next',exact:true})).toBeEnabled()
 await page.getByRole('button',{name:'Next',exact:true}).click()
 await expect(page).toHaveURL(/page=2/)
 await expect(page.getByRole('region',{name:'Card library results'})).toHaveAttribute('aria-busy','false')
 await expect(page.locator('article')).toHaveCount(24)
 const query=page.url(), id=await page.locator('article').first().getAttribute('data-printing-id')
 await page.getByRole('button',{name:'List',exact:true}).click()
 await expect(page.locator('.card-row')).toHaveCount(24)
 await expect(page).toHaveURL(query)
 await page.screenshot({path:'test-results/phase2-list.png',fullPage:true})
 const link=page.locator('.card-row a').first()
 await link.focus();await page.keyboard.press('Enter')
 await expect(page).toHaveURL(new RegExp(`/cards/${id}$`))
 await expect(page.getByRole('heading',{name:'Card text',exact:true})).toBeVisible()
 await expect(page.locator('code')).toHaveText(id!)
 await page.screenshot({path:'test-results/phase2-detail.png',fullPage:true})
 await page.goBack();await expect(page).toHaveURL(query)
 await expect(page.locator('.card-row').first()).toHaveAttribute('data-printing-id',id!)
 await expect(page.getByRole('textbox',{name:'Search cards'})).toHaveValue('a')
 await expect(page.getByLabel('Psychic',{exact:true})).toBeChecked()
 await expect(page.getByLabel('Dragon',{exact:true})).toBeChecked()
 await expect(page.getByLabel('Basic',{exact:true})).toBeChecked()
 await page.goForward();await expect(page.locator('code')).toHaveText(id!)
 await page.reload();await expect(page.locator('code')).toHaveText(id!)
 await page.getByRole('link',{name:'← Back to library'}).click()
 await expect(page).toHaveURL(query)
 await page.getByRole('button',{name:'Gallery',exact:true}).click()
 await expect(page.locator('.card-tile').first()).toHaveAttribute('data-printing-id',id!)
 await page.reload();await expect(page.getByLabel('Psychic',{exact:true})).toBeChecked()
 await expect(page.getByRole('textbox',{name:'Search cards'})).toHaveValue('a')
 await page.screenshot({path:'test-results/phase2-gallery.png',fullPage:true})
})

test('direct missing printing shows a useful error',async({page})=>{
 await page.goto('/cards/nonexistent-999')
 await expect(page.getByRole('alert')).toContainText('exact printing was not found')
 await page.getByRole('link',{name:'← Back to library'}).click()
 await expect(page.locator('article')).toHaveCount(24)
})
