import { test, expect } from '@playwright/test'

test('empty Energy and repeated Trainer selections agree with authoritative category results',async({page,request})=>{
 const read=async(query:string)=>{
  const response=await request.get('/api/v1/cards?'+query)
  expect(response.ok()).toBeTruthy();return response.json()
 }
 const energy=await read('category=Energy&page_size=24')
 await page.goto('/?category=Energy')
 await expect(page.getByTestId('result-progress')).toHaveText(`${Math.min(24,energy.total)}/${energy.total}`)
 await page.getByLabel('Special Energy',{exact:true}).click()
 const special=await read('category=Energy&energy_types=Special&page_size=24')
 await expect(page.getByTestId('result-progress')).toHaveText(`${Math.min(24,special.total)}/${special.total}`)
 await page.getByLabel('Basic Energy',{exact:true}).click()
 const both=await read('category=Energy&energy_types=Special&energy_types=Normal&page_size=24')
 await expect(page.getByTestId('result-progress')).toHaveText(`${Math.min(24,both.total)}/${both.total}`)
 expect(both.total).toBeGreaterThanOrEqual(special.total)
 await page.getByLabel('Special Energy',{exact:true}).click()
 await page.getByLabel('Basic Energy',{exact:true}).click()
 await expect(page.getByTestId('result-progress')).toHaveText(`${Math.min(24,energy.total)}/${energy.total}`)
 expect(new URL(page.url()).searchParams.getAll('energy_types')).toEqual([])
 await page.getByRole('button',{name:'Trainers',exact:true}).click()
 await page.getByLabel('Supporter',{exact:true}).click()
 await page.getByLabel('H',{exact:true}).click()
 const h=await read('category=Trainer&trainer_types=Supporter&regulation_marks=H&page_size=24')
 await expect(page.getByTestId('result-progress')).toHaveText(`${Math.min(24,h.total)}/${h.total}`)
 await page.getByLabel('J',{exact:true}).click()
 const hj=await read('category=Trainer&trainer_types=Supporter&regulation_marks=H&regulation_marks=J&page_size=24')
 await expect(page.getByTestId('result-progress')).toHaveText(`${Math.min(24,hj.total)}/${hj.total}`)
 expect(hj.total).toBeGreaterThanOrEqual(h.total)
 expect(new URL(page.url()).searchParams.getAll('regulation_marks')).toEqual(['H','J'])
 await page.getByRole('button',{name:'Clear filters',exact:true}).click()
 const trainers=await read('category=Trainer&page_size=24')
 await expect(page.getByTestId('result-progress')).toHaveText(`${Math.min(24,trainers.total)}/${trainers.total}`)
})

test('Ability, cumulative pagination, per-category state and browser history use real data',async({page,request})=>{
 const query='category=Pokemon&pokemon_types=Psychic&pokemon_types=Dragon&stages=Basic&ability=Yes'
 const response=await request.get('/api/v1/cards?'+query+'&page_size=24')
 expect(response.ok()).toBeTruthy()
 let expected=await response.json()
 expect(expected.total).toBeGreaterThan(0)
 await page.goto('/?'+query)
 await expect(page.getByLabel('Yes',{exact:true})).toBeChecked()
 await expect(page.getByTestId('result-progress')).toHaveText(`${Math.min(24,expected.total)}/${expected.total}`)
 for(const card of expected.cards){
  const detail=await (await request.get('/api/v1/cards/'+encodeURIComponent(card.id))).json()
  expect(detail.card.abilities.some((ability:{type:string})=>ability.type==='Ability')).toBe(true)
  expect(detail.card.stage).toBe('Basic')
  expect(detail.card.types.some((type:string)=>['Psychic','Dragon'].includes(type))).toBe(true)
 }
 // Representative grouping may put this narrow query on a single partial page.
 // Broaden only the type family to exercise Ability pagination on real cards.
 await page.getByLabel('Psychic',{exact:true}).click()
 await page.getByLabel('Dragon',{exact:true}).click()
 expected=await (await request.get('/api/v1/cards?category=Pokemon&stages=Basic&ability=Yes&page_size=24')).json()
 expect(expected.total).toBeGreaterThan(24)
 await expect(page.getByTestId('result-progress')).toHaveText(`24/${expected.total}`)
 await page.getByRole('button',{name:'Next',exact:true}).click()
 await expect(page.getByTestId('result-progress')).toHaveText(`${Math.min(48,expected.total)}/${expected.total}`)
 const pokemonURL=page.url()
 const printing=await page.locator('article').first().getAttribute('data-printing-id')
 await page.getByRole('button',{name:'Trainers',exact:true}).click()
 await page.getByRole('textbox',{name:'Search cards'}).fill('Boss')
 await expect(page.locator('article').first()).toContainText('Boss')
 const trainerURL=page.url()
 await page.getByRole('button',{name:'Energy',exact:true}).click()
 await page.getByLabel('Special Energy',{exact:true}).click()
 await expect(page.locator('article').first()).toContainText('Special Energy')
 const energyURL=page.url()
 await page.getByRole('button',{name:'Pokémon',exact:true}).click()
 await expect(page).toHaveURL(pokemonURL)
 await expect(page.locator('article').first()).toHaveAttribute('data-printing-id',printing!)
 await page.getByRole('button',{name:'Trainers',exact:true}).click();await expect(page).toHaveURL(trainerURL)
 await page.getByRole('button',{name:'Energy',exact:true}).click();await expect(page).toHaveURL(energyURL)
 await page.goBack();await expect(page).toHaveURL(trainerURL)
 await page.goForward();await expect(page).toHaveURL(energyURL)
 await page.getByRole('button',{name:'Pokémon',exact:true}).click();await expect(page).toHaveURL(pokemonURL)
 await page.reload();await expect(page.getByLabel('Yes',{exact:true})).toBeChecked()
 await expect(page.getByTestId('result-progress')).toHaveText(`${Math.min(48,expected.total)}/${expected.total}`)
 await page.getByLabel('Yes',{exact:true}).click()
 expect(new URL(page.url()).searchParams.has('ability')).toBe(false)
 expect(new URL(page.url()).searchParams.has('page')).toBe(false)
})

test('Ability No/both/empty and curated Basic Energy remain server-authoritative',async({page,request})=>{
 const base='category=Pokemon&stages=Basic&pokemon_types=Psychic&pokemon_types=Dragon'
 const read=async(query:string)=>(await request.get('/api/v1/cards?'+query+'&page_size=24')).json()
 const unrestricted=await read(base)
 const no=await read(base+'&ability=No')
 const yes=await read(base+'&ability=Yes')
 expect(no.total+yes.total).toBe(unrestricted.total)
 await page.goto('/?'+base+'&ability=No')
 await expect(page.getByLabel('No',{exact:true})).toBeChecked()
 await expect(page.getByTestId('result-progress')).toHaveText(`${Math.min(24,no.total)}/${no.total}`)
 for(const card of no.cards) {
  const detail=await (await request.get('/api/v1/cards/'+card.id)).json()
  expect((detail.card.abilities||[]).some((a:{type:string})=>a.type==='Ability')).toBe(false)
 }
 const legends=await page.locator('legend').allTextContents()
 expect(legends.indexOf('Ability')).toBe(legends.indexOf('Stage')+1)
 expect(legends.indexOf('Regulation mark')).toBe(legends.indexOf('Ability')+1)
 await page.getByLabel('Yes',{exact:true}).click()
 await expect(page.getByTestId('result-progress')).toHaveText(`${Math.min(24,unrestricted.total)}/${unrestricted.total}`)
 await page.reload();await expect(page.getByLabel('No',{exact:true})).toBeChecked()
 await expect(page.getByLabel('Yes',{exact:true})).toBeChecked()
 await page.getByLabel('No',{exact:true}).click()
 await expect(page.getByTestId('result-progress')).toHaveText(`${Math.min(24,yes.total)}/${yes.total}`)
 await page.getByLabel('Yes',{exact:true}).click()
 await expect(page.getByTestId('result-progress')).toHaveText(`${Math.min(24,unrestricted.total)}/${unrestricted.total}`)
 const energy=await (await request.get('/api/v1/cards?category=Energy&page_size=50')).json()
 expect(energy.next_page).toBeNull()
 const basic=energy.cards.filter((c:{name:string})=>/^(Basic )?(Grass|Fire|Water|Lightning|Psychic|Fighting|Darkness|Metal|Fairy) Energy$/.test(c.name))
 expect(basic.length).toBe(8) // Current synchronized Standard pool, no Fairy.
 expect(new Set(basic.map((c:{name:string})=>c.name.replace(/^Basic /,''))).size).toBe(8)
 await page.getByRole('button',{name:'Energy',exact:true}).click()
 for(const card of basic) {
  const tile=page.locator(`article[data-printing-id="${card.id}"]`)
  await expect(tile).toHaveCount(1)
  await tile.scrollIntoViewIfNeeded()
  await expect.poll(()=>tile.locator('img').evaluateAll(images=>images.some(img=>(img as HTMLImageElement).naturalWidth>0)),{timeout:45000}).toBe(true)
 }
 await page.screenshot({path:'test-results/phase2-energy-curated.png',fullPage:true})
})
