import { test, expect } from '@playwright/test'

test('real Card → Archetype → Tournament Deck → Card research loop preserves context and active deck',async({page,request},info)=>{
 test.setTimeout(120000)
 const before=await(await request.get('/api/v1/deck-workspace')).json()
 const pool=await(await request.get('/api/v1/cards?category=Trainer&q=Ultra+Ball')).json(),card=pool.cards[0]
 const research=await(await request.get(`/api/v1/competitive/cards/${card.id}`)).json()
 const archetype=research.archetypes.find((a:any)=>a.id==='/decks/284')
 expect(archetype.eligible_decks).toBeGreaterThanOrEqual(15)
 await page.goto(`/deck-builder/cards/${card.id}`)
 const row=page.locator('.competitive-dashboard tr').filter({has:page.getByRole('link',{name:archetype.name,exact:true})})
 await row.getByRole('link',{name:`Explore ${archetype.eligible_decks} decks →`,exact:true}).click()
 await expect(page).toHaveURL(new RegExp(`/deck-builder/archetypes/${archetype.research_id}\\?window=30#tournament-evidence`))
 const evidence=page.getByRole('region',{name:'Tournament decks'})
 await expect(evidence.getByText(`${archetype.eligible_decks} eligible mapped decks`,{exact:true})).toBeVisible()
 await expect(page.getByRole('complementary',{name:'Active deck'})).toBeVisible()
 await evidence.screenshot({path:info.outputPath('archetype-evidence.png')})
 const composite=page.getByRole('region',{name:'Archetype Composite'})
 await expect(composite.getByText('60 cards',{exact:true})).toBeAttached()
 await page.locator('.research-page').evaluate(e=>e.scrollTop=0)
 await page.screenshot({path:info.outputPath('archetype-composite.png')})
 await page.getByRole('group',{name:'Competitive timeframe'}).getByRole('button',{name:'90D',exact:true}).click()
 await expect(page).toHaveURL(/window=90/)
 await expect(page.getByRole('heading',{name:archetype.name,exact:true})).toBeVisible()
 await page.getByRole('button',{name:'List',exact:true}).click()
 await evidence.getByRole('button',{name:'Next decks'}).click()
 await expect(evidence.getByText('Page 2',{exact:true})).toBeVisible()
 const archetypeURL=page.url()
 const sourceLink=evidence.locator('.evidence-list a').first(),label=await sourceLink.innerText()
 await sourceLink.click()
 await expect(page.getByRole('heading',{name:'Tournament Deck Research'})).toBeVisible()
 await expect(page.getByText('ACTUAL OBSERVED TOURNAMENT DECK · LIMITLESS')).toBeVisible()
 await expect(page.getByText('60 cards',{exact:true})).toBeVisible()
 await expect(page.locator('.research-cards .quantity-row,.research-cards .deck-stepper')).toHaveCount(0)
 await page.reload()
 await expect(page.getByRole('heading',{name:'Tournament Deck Research'})).toBeVisible()
 await expect(page.getByRole('button',{name:'List',exact:true})).toHaveAttribute('aria-pressed','true')
 await page.getByRole('button',{name:'Gallery',exact:true}).click()
 await page.screenshot({path:info.outputPath('tournament-deck.png')})
 const tile=page.locator('.research-cards .card-tile').first(),image=tile.locator('img')
 await expect(image).toBeVisible();await image.hover()
 await expect(page.locator('.competitive-popup')).toBeVisible()
 await page.mouse.move(1,1);await expect(page.locator('.competitive-popup')).toHaveCount(0)
 await tile.locator('.card-link').click();await expect(page).toHaveURL(/\/deck-builder\/cards\/.*window=90/)
 await expect(page.getByRole('heading',{name:'Competitive research'})).toBeVisible()
 await page.getByRole('link',{name:'← Back to research',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Tournament Deck Research'})).toBeVisible()
 await page.getByRole('link',{name:'← Back to research context',exact:true}).click()
 await expect(page).toHaveURL(archetypeURL)
 await expect(evidence.getByText('Page 2',{exact:true})).toBeVisible()
 await expect(evidence.locator('.evidence-list a').first()).toHaveText(label)
 await expect(page.getByRole('button',{name:'List',exact:true})).toHaveAttribute('aria-pressed','true')
 expect(await(await request.get('/api/v1/deck-workspace')).json()).toEqual(before)
})

test('real small sample stays explorable and direct Format URL truthfully has no configured evidence',async({page,request},info)=>{
 const card=(await(await request.get('/api/v1/cards?category=Trainer&q=Ultra+Ball')).json()).cards[0]
 const r=await(await request.get(`/api/v1/competitive/cards/${card.id}`)).json()
 const a=r.archetypes.find((a:any)=>a.eligible_decks>0&&a.eligible_decks<15&&a.id!=='unknown')
 expect(a).toBeTruthy()
 await page.goto(`/archetypes/${a.research_id}?window=30`)
 await expect(page.getByRole('heading',{name:a.name,exact:true})).toBeVisible()
 await expect(page.getByText(`Limited evidence — ${a.eligible_decks} published decklists. Insufficient sample for prevalence.`,{exact:true})).toBeVisible()
 const evidence=page.getByRole('region',{name:'Tournament decks'})
 await expect(evidence.getByText(`${a.eligible_decks} eligible mapped decks`,{exact:true})).toBeAttached()
 await page.screenshot({path:info.outputPath('small-sample.png')})
 await page.reload();await expect(page.getByRole('heading',{name:a.name,exact:true})).toBeVisible()
 await page.goto(`/archetypes/${a.research_id}?window=format`)
 await expect(page.getByText('Format start not configured or unavailable.',{exact:true}).first()).toBeVisible()
 await expect(page.getByRole('button',{name:'Format',exact:true})).toBeDisabled()
 await expect(evidence.locator('li')).toHaveCount(0)
})

test('unmapped evidence remains inspectable in a deterministic partial-deck fixture',async({page,request})=>{
 const card=(await(await request.get('/api/v1/cards?category=Trainer&q=Ultra+Ball')).json()).cards[0]
 await page.route('**/api/v1/research/tournament-decks/partial',route=>route.fulfill({json:{source:'limitless-main',observation:{id:'partial',event_id:'1',event:'Fixture event',date:'2026-09-20',player:'Observed player',placement:2,archetype_id:'known',archetype:'Fixture archetype',source_url:null,event_url:'https://limitlesstcg.com/tournaments/1',mapped:false,fetched_at:'2026-09-21'},card_count:60,mapped_card_count:4,categories:{Trainer:4},cards:[{functional_id:'known',card:{...card,ownership:undefined},owned:0,quantity:4}],published_cards:[{name:'Ultra Ball',set:'T',number:'1',count:4},{name:'Unmapped evidence',set:'X',number:'2',count:56}],unmapped_cards:[{name:'Unmapped evidence',set:'X',number:'2',count:56}],pages:[],presentation_note:'Original source evidence preserved.'}}))
 await page.goto('/tournament-decks/partial?window=30')
 await expect(page.getByText(/Some cards could not be mapped. Showing 4 mapped copies/)).toBeVisible()
 await expect(page.getByText('60 cards',{exact:true})).toBeVisible()
 await expect(page.getByText('56 × Unmapped evidence · X 2')).toHaveCount(2)
 await expect(page.getByRole('button',{name:'Copy to Deck Builder',exact:true})).toBeDisabled()
 await expect(page.getByRole('button',{name:/Add one|Add .* to deck/})).toHaveCount(0)
})
