import {test,expect} from '@playwright/test'

test('tray presentation shares quantities, preserves navigation and uses image-only hover',async({page,request},info)=>{
 const read=async()=> (await request.get('/api/v1/deck-workspace')).json()
 const command=async(body:object)=>{const w=await read();expect((await request.post('/api/v1/deck-workspace',{data:{...body,schema_version:2,revision:w.revision}})).ok()).toBeTruthy()}
 await command({action:'new',discard:true})
 const card=(await(await request.get('/api/v1/cards?category=Trainer&q=Ultra+Ball')).json()).cards[0]
 await command({action:'quantity',printing_id:card.id,delta:1})
 await command({action:'save'})
 await page.goto('/deck-builder')
 const tray=page.getByRole('complementary',{name:'Active deck'})
 await expect(tray.getByRole('button',{name:'List tray view'})).toHaveAttribute('aria-pressed','true')
 const before=await read()
 await tray.getByRole('button',{name:'Gallery tray view'}).click()
 await expect(tray.getByLabel(`${card.name} tray quantity`)).toHaveText('×1')
 expect(await read()).toEqual(before)
 const art=tray.locator('.tray-art-link img').first()
 await expect(art).toBeVisible()
 await tray.getByLabel(`${card.name} tray quantity`).hover();await page.waitForTimeout(650)
 await expect(page.locator('.competitive-popup')).toHaveCount(0)
 await art.hover();await page.waitForTimeout(250);await expect(page.locator('.competitive-popup')).toHaveCount(0)
 await expect(page.locator('.competitive-popup')).toBeVisible()
 await expect(page.locator('.competitive-popup')).toContainText('1 Card in deck')
 await page.mouse.move(1,1)
 await tray.getByRole('button',{name:`Increase ${card.name} in tray`}).click()
 await expect(tray.getByLabel(`${card.name} tray quantity`)).toHaveText('×2')
 await tray.getByRole('button',{name:'List tray view'}).click()
 await expect(tray.locator('.deck-entries output')).toHaveText('2')
 await tray.getByRole('button',{name:`Decrease ${card.name} in tray`}).click()
 await expect(tray.locator('.deck-entries output')).toHaveText('1')
 await tray.getByRole('button',{name:'Gallery tray view'}).click()
 await tray.getByRole('link',{name:`Inspect ${card.name} from tray`}).click()
 await expect(page).toHaveURL(/\/deck-builder\/cards\//)
 await expect(tray.getByRole('button',{name:'Gallery tray view'})).toHaveAttribute('aria-pressed','true')
 await page.locator('.competitive-dashboard').getByRole('link',{name:'Dragapult',exact:true}).click()
 await expect(page).toHaveURL(/archetypes/)
 await page.getByRole('region',{name:'Tournament decks'}).locator('.evidence-list a').first().click()
 await expect(page).toHaveURL(/tournament-decks/)
 await expect(tray.getByLabel(`${card.name} tray quantity`)).toHaveText('×1')
 await page.setViewportSize({width:1100,height:800})
 await page.screenshot({path:info.outputPath('tray-gallery.png')})
 await page.reload()
 await expect(tray.getByRole('button',{name:'List tray view'})).toHaveAttribute('aria-pressed','true')
})
